import pushHeaderNav from './js/pushHeaderNav/pushHeaderNav';
import nolink from './js/nolink/nolink';
import scrolltop from './js/scrolltop/scrolltop';
import popup from './js/popup/popup';
import burger from './js/burger/burger';
import sidenav from './js/sidenav/sidenav';
import deliveryDate from './js/deliveryDate/deliveryDate';
import productDescription from './js/productDescription/productDescription';
import loginTabs from './js/loginTabs/loginTabs';
import addClassWoocommerce from './js/addClassWoocommerce/addClassWoocommerce';

pushHeaderNav();
nolink();
scrolltop();
popup();
burger();
sidenav();
deliveryDate();
productDescription();
loginTabs();
addClassWoocommerce();
